package ru.nyxsed.thetome.core.domain.models

enum class RoleId {
    WASHERWOMAN, LIBRARIAN, INVESTIGATOR, CHEF, EMPATH, FORTUNE_TELLER, UNDERTAKER, MONK, RAVENKEEPER,
    VIRGIN, SLAYER, SOLDIER, MAYOR, BUTLER, SAINT, RECLUSE, DRUNK, POISONER, SPY, BARON, SCARLET_WOMAN, IMP,
}