package ru.nyxsed.thetome.core.domain.models

import androidx.annotation.DrawableRes
import kotlinx.serialization.Serializable
import ru.nyxsed.thetome.R

@Serializable
sealed class Scenery(
    val sceneryNameRes: Int,
    @DrawableRes val iconRes: Int = 0,
    val roles: List<Role>,
    val prepareActions: List<Action>,
    val firstNightActions: List<Action>,
    val secondNightActions: List<Action>,
    val dayActions: List<Action>,
    val sceneryTokens: List<Token>,
) {
    @Serializable
    data object TroubleBrewing : Scenery(
        sceneryNameRes = R.string.scenery_name_trouble_brewing,
        iconRes = R.drawable.icon_trouble_brewing,
        roles = listOf(
            Role.Washerwoman,
            Role.Librarian,
            Role.Investigator,
            Role.Chef,
            Role.Empath,
            Role.FortuneTeller,
            Role.Undertaker,
            Role.Monk,
            Role.Ravenkeeper,
            Role.Virgin,
            Role.Slayer,
            Role.Soldier,
            Role.Mayor,
            Role.Butler,
            Role.Saint,
            Role.Recluse,
            Role.Drunk,
            Role.Poisoner,
            Role.Spy,
            Role.Baron,
            Role.ScarletWoman,
            Role.Imp,
        ),
        prepareActions = listOf(
            Action(actionType = ActionType.PLAYER, role = Role.Baron, actionResId = Role.Baron.prepareActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Drunk, actionResId = Role.Drunk.prepareActionId),
            Action(actionType = ActionType.PLAYERS_7, role = null, actionResId = R.string.action_prepare_3_demon_bluffs),
            Action(actionType = ActionType.DAY, role = null, actionResId = R.string.action_prepare_bag),
            Action(actionType = ActionType.PLAYER, role = Role.Washerwoman, actionResId = Role.Washerwoman.prepareActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Librarian, actionResId = Role.Librarian.prepareActionId),
            Action(actionType = ActionType.PLAYER, role = Role.FortuneTeller, actionResId = Role.FortuneTeller.prepareActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Investigator, actionResId = Role.Investigator.prepareActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Recluse, actionResId = Role.Recluse.prepareActionId),
            Action(actionType = ActionType.DAY, role = null, actionResId = R.string.action_start_first_night_phase),
        ),
        firstNightActions = listOf(
            Action(actionType = ActionType.PLAYERS_7, role = null, actionResId = R.string.action_show_demon),
            Action(actionType = ActionType.PLAYERS_7, role = null, actionResId = R.string.action_show_minions_and_bluffs),
            Action(actionType = ActionType.PLAYER, role = Role.Poisoner, actionResId = Role.Poisoner.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Spy, actionResId = Role.Spy.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Washerwoman, actionResId = Role.Washerwoman.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Librarian, actionResId = Role.Librarian.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Investigator, actionResId = Role.Investigator.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Chef, actionResId = Role.Chef.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Empath, actionResId = Role.Empath.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.FortuneTeller, actionResId = Role.FortuneTeller.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Butler, actionResId = Role.Butler.firstNightActionId),
            Action(actionType = ActionType.NIGHT, role = null, actionResId = R.string.action_start_day_phase),
        ),
        secondNightActions = listOf(
            Action(actionType = ActionType.PLAYER, role = Role.Poisoner, actionResId = Role.Poisoner.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Monk, actionResId = Role.Monk.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Spy, actionResId = Role.Spy.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.ScarletWoman, actionResId = Role.ScarletWoman.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Imp, actionResId = Role.Imp.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Ravenkeeper, actionResId = Role.Ravenkeeper.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Undertaker, actionResId = Role.Undertaker.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Empath, actionResId = Role.Empath.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.FortuneTeller, actionResId = Role.FortuneTeller.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Butler, actionResId = Role.Butler.secondNightActionId),
            Action(actionType = ActionType.NIGHT, role = null, actionResId = R.string.action_start_day_phase),
        ),
        dayActions = listOf(
            Action(actionType = ActionType.DAY, role = null, actionResId = R.string.action_voting),
            Action(actionType = ActionType.PLAYER, role = Role.Butler, actionResId = Role.Butler.dayActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Undertaker, actionResId = Role.Undertaker.dayActionId),
            Action(actionType = ActionType.DAY, role = null, actionResId = R.string.action_start_night_phase)
        ),
        sceneryTokens = listOf(Token.Good, Token.Evil, Token.DrunkDrunk)
    )

    @Serializable
    data object UncertainDeath : Scenery(
        sceneryNameRes = R.string.scenery_name_uncertain_death,
        iconRes = R.drawable.icon_uncertain_death,
        roles = listOf(
            Role.Clockmaker,
            Role.Grandmother,
            Role.Librarian,
            Role.Empath,
            Role.FortuneTeller,
            Role.Exorcist,
            Role.Flowergirl,
            Role.Oracle,
            Role.Undertaker,
            Role.Artist,
            Role.Slayer,
            Role.Seamstress,
            Role.Monk,
            Role.Lunatic,
            Role.Mutant,
            Role.Sweetheart,
            Role.Recluse,
            Role.Godfather,
            Role.Assassin,
            Role.ScarletWoman,
            Role.Marionette,
            Role.NoDashii,
            Role.Pukka,
        ),
        prepareActions = listOf(
            Action(actionType = ActionType.PLAYER, role = Role.Godfather, actionResId = Role.Godfather.prepareActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Marionette, actionResId = Role.Marionette.prepareActionId),
            Action(actionType = ActionType.PLAYERS_7, role = null, actionResId = R.string.action_prepare_3_demon_bluffs),
            Action(actionType = ActionType.DAY, role = null, actionResId = R.string.action_prepare_bag),
            Action(actionType = ActionType.PLAYER, role = Role.Librarian, actionResId = Role.Librarian.prepareActionId),
            Action(actionType = ActionType.PLAYER, role = Role.FortuneTeller, actionResId = Role.FortuneTeller.prepareActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Recluse, actionResId = Role.Recluse.prepareActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Grandmother, actionResId = Role.Grandmother.prepareActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Lunatic, actionResId = Role.Lunatic.prepareActionId),
            Action(actionType = ActionType.PLAYER, role = Role.NoDashii, actionResId = Role.NoDashii.prepareActionId),
            Action(actionType = ActionType.DAY, role = null, actionResId = R.string.action_start_first_night_phase),
        ),
        firstNightActions = listOf(
            Action(actionType = ActionType.PLAYERS_7, role = null, actionResId = R.string.action_show_demon),
            Action(actionType = ActionType.PLAYER, role = Role.Lunatic, actionResId = Role.Lunatic.firstNightActionId),
            Action(actionType = ActionType.PLAYERS_7, role = null, actionResId = R.string.action_show_minions_and_bluffs),
            Action(actionType = ActionType.PLAYER, role = Role.Godfather, actionResId = Role.Godfather.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Pukka, actionResId = Role.Pukka.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Librarian, actionResId = Role.Librarian.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Empath, actionResId = Role.Empath.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.FortuneTeller, actionResId = Role.FortuneTeller.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Grandmother, actionResId = Role.Grandmother.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Clockmaker, actionResId = Role.Clockmaker.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Seamstress, actionResId = Role.Seamstress.firstNightActionId),
            Action(actionType = ActionType.NIGHT, role = null, actionResId = R.string.action_start_day_phase),
        ),
        secondNightActions = listOf(
            Action(actionType = ActionType.PLAYER, role = Role.Monk, actionResId = Role.Monk.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.ScarletWoman, actionResId = Role.ScarletWoman.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Lunatic, actionResId = Role.Lunatic.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Exorcist, actionResId = Role.Exorcist.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Pukka, actionResId = Role.Pukka.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.NoDashii, actionResId = Role.NoDashii.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Assassin, actionResId = Role.Assassin.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Godfather, actionResId = Role.Godfather.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Sweetheart, actionResId = Role.Sweetheart.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Grandmother, actionResId = Role.Grandmother.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Empath, actionResId = Role.Empath.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.FortuneTeller, actionResId = Role.FortuneTeller.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Undertaker, actionResId = Role.Undertaker.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Flowergirl, actionResId = Role.Flowergirl.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Oracle, actionResId = Role.Oracle.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Seamstress, actionResId = Role.Seamstress.secondNightActionId),
            Action(actionType = ActionType.NIGHT, role = null, actionResId = R.string.action_start_day_phase),
        ),
        dayActions = listOf(
            Action(actionType = ActionType.PLAYER, role = Role.Flowergirl, actionResId = Role.Flowergirl.dayActionId),
            Action(actionType = ActionType.DAY, role = null, actionResId = R.string.action_voting),
            Action(actionType = ActionType.PLAYER, role = Role.Undertaker, actionResId = Role.Undertaker.dayActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Sweetheart, actionResId = Role.Sweetheart.dayActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Godfather, actionResId = Role.Godfather.dayActionId),
            Action(actionType = ActionType.DAY, role = null, actionResId = R.string.action_start_night_phase)
        ),
        sceneryTokens = listOf(Token.Good, Token.Evil, Token.MarionetteMarionette),
    )

    @Serializable
    data object BadMoonRising : Scenery(
        sceneryNameRes = R.string.scenery_name_bad_moon_rising,
        iconRes = R.drawable.icon_bad_moon_rising,
        roles = listOf(
            Role.Grandmother,
            Role.Sailor,
            Role.Chambermaid,
            Role.Exorcist,
            Role.Innkeeper,
            Role.Gambler,
            Role.Gossip,
            Role.Courtier,
            Role.Professor,
            Role.Minstrel,
            Role.TeaLady,
            Role.Pacifist,
            Role.Fool,
            Role.Goon,
            Role.Lunatic,
            Role.Tinker,
            Role.Moonchild,
            Role.Godfather,
            Role.DevilsAdvocate,
            Role.Assassin,
            Role.Mastermind,
            Role.Zombuul,
            Role.Pukka,
            Role.Shabaloth,
            Role.Po,
        ),
        prepareActions = listOf(
            Action(actionType = ActionType.PLAYER, role = Role.Godfather, actionResId = Role.Godfather.prepareActionId),
            Action(actionType = ActionType.PLAYERS_7, role = null, actionResId = R.string.action_prepare_3_demon_bluffs),
            Action(actionType = ActionType.DAY, role = null, actionResId = R.string.action_prepare_bag),
            Action(actionType = ActionType.PLAYER, role = Role.Grandmother, actionResId = Role.Grandmother.prepareActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Lunatic, actionResId = Role.Lunatic.prepareActionId),
            Action(actionType = ActionType.PLAYER, role = Role.TeaLady, actionResId = Role.TeaLady.prepareActionId),
            Action(actionType = ActionType.DAY, role = null, actionResId = R.string.action_start_first_night_phase),
        ),
        firstNightActions = listOf(
            Action(actionType = ActionType.PLAYERS_7, role = null, actionResId = R.string.action_show_demon),
            Action(actionType = ActionType.PLAYER, role = Role.Lunatic, actionResId = Role.Lunatic.firstNightActionId),
            Action(actionType = ActionType.PLAYERS_7, role = null, actionResId = R.string.action_show_minions_and_bluffs),
            Action(actionType = ActionType.PLAYER, role = Role.Goon, actionResId = Role.Goon.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Sailor, actionResId = Role.Sailor.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Courtier, actionResId = Role.Courtier.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Godfather, actionResId = Role.Godfather.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.DevilsAdvocate, actionResId = Role.DevilsAdvocate.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Pukka, actionResId = Role.Pukka.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Fool, actionResId = Role.Fool.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Grandmother, actionResId = Role.Grandmother.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Chambermaid, actionResId = Role.Chambermaid.firstNightActionId),
            Action(actionType = ActionType.NIGHT, role = null, actionResId = R.string.action_start_day_phase),
        ),
        secondNightActions = listOf(
            Action(actionType = ActionType.PLAYER, role = Role.Goon, actionResId = Role.Goon.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Sailor, actionResId = Role.Sailor.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Innkeeper, actionResId = Role.Innkeeper.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Courtier, actionResId = Role.Courtier.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Gambler, actionResId = Role.Gambler.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.DevilsAdvocate, actionResId = Role.DevilsAdvocate.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Lunatic, actionResId = Role.Lunatic.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Exorcist, actionResId = Role.Exorcist.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Zombuul, actionResId = Role.Zombuul.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Pukka, actionResId = Role.Pukka.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Shabaloth, actionResId = Role.Shabaloth.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Po, actionResId = Role.Po.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Fool, actionResId = Role.Fool.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Assassin, actionResId = Role.Assassin.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Godfather, actionResId = Role.Godfather.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Professor, actionResId = Role.Professor.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Gossip, actionResId = Role.Gossip.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Moonchild, actionResId = Role.Moonchild.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Grandmother, actionResId = Role.Grandmother.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Chambermaid, actionResId = Role.Chambermaid.secondNightActionId),
            Action(actionType = ActionType.NIGHT, role = null, actionResId = R.string.action_start_day_phase),
        ),
        dayActions = listOf(
            Action(actionType = ActionType.PLAYER, role = Role.Innkeeper, actionResId = Role.Innkeeper.dayActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Moonchild, actionResId = Role.Sailor.dayActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Gossip, actionResId = Role.Gossip.dayActionId),
            Action(actionType = ActionType.DAY, role = null, actionResId = R.string.action_voting),
            Action(actionType = ActionType.PLAYER, role = Role.DevilsAdvocate, actionResId = Role.DevilsAdvocate.dayActionId),
            Action(actionType = ActionType.PLAYER, role = Role.TeaLady, actionResId = Role.TeaLady.dayActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Pacifist, actionResId = Role.Pacifist.dayActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Godfather, actionResId = Role.Godfather.dayActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Minstrel, actionResId = Role.Minstrel.dayActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Fool, actionResId = Role.Fool.dayActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Mastermind, actionResId = Role.Mastermind.dayActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Zombuul, actionResId = Role.Zombuul.dayActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Sailor, actionResId = Role.Sailor.dayActionId),
            Action(actionType = ActionType.DAY, role = null, actionResId = R.string.action_start_night_phase)
        ),
        sceneryTokens = listOf(Token.Good, Token.Evil),
    )

    @Serializable
    data object SectsNViolets : Scenery(
        sceneryNameRes = R.string.scenery_name_sects_and_violets,
        iconRes = R.drawable.icon_sects_and_violets,
        roles = listOf(
            Role.Clockmaker,
            Role.Dreamer,
            Role.SnakeCharmer,
            Role.Mathematician,
            Role.Flowergirl,
            Role.TownCrier,
            Role.Oracle,
            Role.Savant,
            Role.Seamstress,
            Role.Philosopher,
            Role.Artist,
            Role.Juggler,
            Role.Sage,
            Role.Mutant,
            Role.Sweetheart,
            Role.Barber,
            Role.Klutz,
            Role.EvilTwin,
            Role.Witch,
            Role.Cerenovus,
            Role.PitHag,
            Role.FangGu,
            Role.Vigormortis,
            Role.NoDashii,
            Role.Vortox,
        ),
        prepareActions = listOf(
            Action(actionType = ActionType.PLAYER, role = Role.FangGu, actionResId = Role.FangGu.prepareActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Vigormortis, actionResId = Role.Vigormortis.prepareActionId),
            Action(actionType = ActionType.PLAYERS_7, role = null, actionResId = R.string.action_prepare_3_demon_bluffs),
            Action(actionType = ActionType.DAY, role = null, actionResId = R.string.action_prepare_bag),
            Action(actionType = ActionType.PLAYER, role = Role.Vortox, actionResId = Role.Vortox.prepareActionId),
            Action(actionType = ActionType.PLAYER, role = Role.NoDashii, actionResId = Role.NoDashii.prepareActionId),
            Action(actionType = ActionType.PLAYER, role = Role.EvilTwin, actionResId = Role.EvilTwin.prepareActionId),
            Action(actionType = ActionType.DAY, role = null, actionResId = R.string.action_start_first_night_phase),
        ),
        firstNightActions = listOf(
            Action(actionType = ActionType.PLAYERS_7, role = null, actionResId = R.string.action_show_demon),
            Action(actionType = ActionType.PLAYERS_7, role = null, actionResId = R.string.action_show_minions_and_bluffs),
            Action(actionType = ActionType.PLAYER, role = Role.Philosopher, actionResId = Role.Philosopher.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.SnakeCharmer, actionResId = Role.SnakeCharmer.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.EvilTwin, actionResId = Role.EvilTwin.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Witch, actionResId = Role.Witch.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Cerenovus, actionResId = Role.Cerenovus.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Clockmaker, actionResId = Role.Clockmaker.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Dreamer, actionResId = Role.Dreamer.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Seamstress, actionResId = Role.Seamstress.firstNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Mathematician, actionResId = Role.Mathematician.firstNightActionId),
            Action(actionType = ActionType.NIGHT, role = null, actionResId = R.string.action_start_day_phase),
        ),
        secondNightActions = listOf(
            Action(actionType = ActionType.PLAYER, role = Role.Philosopher, actionResId = Role.Philosopher.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.SnakeCharmer, actionResId = Role.SnakeCharmer.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Witch, actionResId = Role.Witch.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Cerenovus, actionResId = Role.Cerenovus.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.PitHag, actionResId = Role.PitHag.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.FangGu, actionResId = Role.FangGu.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Vigormortis, actionResId = Role.Vigormortis.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.NoDashii, actionResId = Role.NoDashii.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Vortox, actionResId = Role.Vortox.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Barber, actionResId = Role.Barber.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Sweetheart, actionResId = Role.Sweetheart.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Sage, actionResId = Role.Sage.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Dreamer, actionResId = Role.Dreamer.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Flowergirl, actionResId = Role.Flowergirl.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.TownCrier, actionResId = Role.TownCrier.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Oracle, actionResId = Role.Oracle.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Seamstress, actionResId = Role.Seamstress.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Juggler, actionResId = Role.Juggler.secondNightActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Mathematician, actionResId = Role.Mathematician.secondNightActionId),
            Action(actionType = ActionType.NIGHT, role = null, actionResId = R.string.action_start_day_phase),
        ),
        dayActions = listOf(
            Action(actionType = ActionType.PLAYER, role = Role.Vortox, actionResId = Role.Vortox.dayActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Flowergirl, actionResId = Role.Flowergirl.dayActionId),
            Action(actionType = ActionType.DAY, role = null, actionResId = R.string.action_voting),
            Action(actionType = ActionType.PLAYER, role = Role.Juggler, actionResId = Role.Juggler.dayActionId),
            Action(actionType = ActionType.PLAYER, role = Role.TownCrier, actionResId = Role.TownCrier.dayActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Sweetheart, actionResId = Role.Sweetheart.dayActionId),
            Action(actionType = ActionType.PLAYER, role = Role.Barber, actionResId = Role.Barber.dayActionId),
            Action(actionType = ActionType.DAY, role = null, actionResId = R.string.action_start_night_phase)
        ),
        sceneryTokens = listOf(Token.Good, Token.Evil),
    )


    companion object {
        val all: List<Scenery> = listOf(
            TroubleBrewing,
            BadMoonRising,
            SectsNViolets,
            UncertainDeath,
        )
    }
}